apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab302app
  namespace: lab302
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab302app
  template:
    metadata:
      labels:
        app: lab302app
    spec:
      containers:
        - name: lab302app
          image: lab302acr.azurecr.io/lab302:1.0.24
          ports:
            - containerPort: 8080

