name: Build and Push Image

on:
  push:
    branches: [ dev ]

env:
  IMAGE_NAME: lab302
  ACR_NAME: lab302acr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Azure Container Registry Name
      run: echo ${{ env.ACR_NAME }}

    - run: |
        az acr login --name ${{ env.ACR_NAME }}

    - run: |
        TAG=1.0.${{ github.run_number }}
        ACR=$(az acr show --name ${{ env.ACR_NAME }} --query loginServer -o tsv)
        docker build -t $ACR/${{ env.IMAGE_NAME }}:$TAG .
        docker push $ACR/${{ env.IMAGE_NAME }}:$TAG