name: Build and Push Image

on:
  push:
    branches: [ dev ]

env:
  IMAGE_NAME: lab302
  ACR_NAME: lab302acr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Validate ACR Access
      run: az acr show --name ${{ env.ACR_NAME }} -o table
