name: Build and Push Image

on:
  push:
    branches: [ dev ]

env:
  IMAGE_NAME: lab302
  ACR_NAME: lab302acr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Debug ACR visibility
      run: |
        az account show
        az acr list -o table

    - name: Get ACR LoginServer
      id: acr-login-server
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --query loginServer --output tsv)
        echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
        echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"



